name: Deploy Workflow

on:
  push: 
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to test-server
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.40.234
          username: deploy
          key: ${{ secrets.OMG_SECRET }}
          port: 22
          script: |
            php artisan down
            cd /var/www/html/youdomain.com
            git checkout main
            git reset --hard
            git pull origin main
            composer install
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan up

            
            
