name: Deploy Workflow

on:
  push: 
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to test-server
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.40.234
          username: deploy
          key: ${{ secrets.OMG_SECRET }}
          port: 22
          proxy_key: ${{ secrets.OMG_SECRET }}
          script: |
            cd /var/www/html/youdomain.com
            ls -al
            
            
