name: Deploy Workflow

on:
  push: 
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SSH-Agent
        id: ssh-agent
        uses: appleboy/ssh-action@master
        with:
          ssh-private-key: ${{ secrets.OMG_SECRET }}
          start: true
          env: SSH_AUTH_SOCK


      - name: Deploy to test-server
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.40.234
          username: deploy
          key: ${{ secrets.OMG_SECRET }}
          port: 22
          key_path: "/home/deploy/.ssh"
          script: |
            cd /var/www/html/youdomain.com
            composer require laravel/envoy
            php vendor/bin/envoy run deploy


# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup SSH key
#       uses: appleboy/ssh-action@master
#       with:
#         ssh_private_key: ${{ secrets.OMG_SECRET }}

#     - name: Deploy code
#       run: |
#         git remote add production ssh://<username>@<hostname>/<path>
#         git push production main

#     - name: Copy ssh key
#       run: ssh-copy-id <username>@<hostname>
