name: Deploy Workflow

on:
  push: 
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Cache composer dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor
      #     key: composer-${{ hashFiles('composer.lock') }}

      # - name: Install composer dependencies
      #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      # - name: Prepare Laravel Application
      #   run: |
      #     cp .env.example .env
      #     php artisan key:generate

      # - name: Prepare for deployment
      #   run: composer require laravel/envoy

      - name: SSH-Agent
        id: ssh-agent
        uses: appleboy/ssh-action@master
        with:
          ssh-private-key: ${{ secrets.OMG_SECRET }}
          start: true
          env: SSH_AUTH_SOCK


      - name: Deploy to test-server
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.40.234
          username: deploy
          key: ${{ secrets.OMG_SECRET }}
          port: 22
          proxy_key: ${{ secrets.OMG_SECRET }}
          script: |
            cd /var/www/html/youdomain.com
            composer require laravel/envoy
            php vendor/bin/envoy run deploy
