name: Deploy Workflow

on:
  push: 
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.40.234
          username: deploy
          key: ${{ secrets.OMG_SECRET }}
          port: 22
          ssh_private_key: ${{ secrets.OMG_SECRET }}
          ssh_add: true
      
      - name: Change directories
        run:  cd /var/www/html/youdomain.com

      - name: Show the current folder
        run: ls -al